# 1. Calculate the total revenue generated by two product categories in a store

print("1. -----------------------------------------------------------------------")
import numpy as np
total_revenue =[]
sum = 0
category1_revenue = np.array([500, 600, 700, 550])
category2_revenue = np.array([450, 700, 800,600])
for i in range(len(category1_revenue)):
    total_revenue.append(category1_revenue[i]+category2_revenue[i])
print("Total Revenue: ",np.array(total_revenue))

# 2. Calculate the profit made by a company

print("2. -----------------------------------------------------------------------")
import numpy as np
profit =[]
sum = 0
revenue = np.array([10000, 12000, 11000, 10500])
expenses = np.array([4000, 5000, 4500, 4800])
for i in range(len(revenue)):
    profit.append(revenue[i]-expenses[i])
print("Profit: ",np.array(profit))

# 3. Determine which products in a store are out of stock (quantity is 0).

print("3. -----------------------------------------------------------------------")
import numpy as np
out_stock = []
inventory = np.array([10, 0, 5, 0, 20, 0])
for i in range(len(inventory)):
    if(inventory[i] == 0):
        out_stock.append(inventory[i]) 
print("Out of Stock Products: ",np.array(out_stock))

# 4. Calculate the total cost of items in a shopping cart, considering the quantity and price per item.

print("4. -----------------------------------------------------------------------")
import numpy as np
cost = []
total = 0
quantity = np.array([2, 3, 4, 1])
price_per_item = np.array([10.0, 5.0, 8.0, 12.0])
for i in range(len(quantity)):
    total += (quantity[i]*price_per_item[i])
    cost.append(quantity[i]*price_per_item[i])
print("Total per item: ",np.array(cost))
print("Total Cost: ",total)